#release configuration
#Wed Jun 28 15:56:41 MSK 2023
completedPhase=end-release
exec.pomFileName=pom.xml
exec.snapshotReleasePluginAllowed=false
pinExternals=false
preparationGoals=clean verify
project.dev.ru.spmi.backend\:university=0.0.3-SNAPSHOT
project.rel.ru.spmi.backend\:university=0.0.2
project.scm.ru.spmi.backend\:university.connection=scm\:git\://git01.resp.man.spmi.ru/Common/ngAngular
project.scm.ru.spmi.backend\:university.developerConnection=scm\:git\://git01.resp.man.spmi.ru/Common/ngAngular
project.scm.ru.spmi.backend\:university.tag=HEAD
project.scm.ru.spmi.backend\:university.url=//git01.resp.man.spmi.ru/Common/ngAngular
projectVersionPolicyId=default
pushChanges=true
releaseStrategyId=default
remoteTagging=true
scm.branchCommitComment=@{prefix} prepare branch @{releaseLabel}
scm.commentPrefix=[maven-release-plugin] 
scm.developmentCommitComment=@{prefix} prepare for next development iteration
scm.releaseCommitComment=@{prefix} prepare release @{releaseLabel}
scm.rollbackCommitComment=@{prefix} rollback the release of @{releaseLabel}
scm.tag=university-0.0.2
scm.tagNameFormat=@{project.artifactId}-@{project.version}
scm.url=scm\:git\://git01.resp.man.spmi.ru/Common/ngAngular
