spring:
#    profiles:
#        active: test
    jpa:
        show-sql: false
        properties:
            hibernate:
    datasource:
        url: jdbc:postgresql://localhost:5432/dbusareboot?public
        username: usareboot
        password: Katerina_2022
        driver-class-name: org.postgresql.Driver

vk:
    api:
        groupId: '224336762'
        chatId: '4'
        version: '5.139'
        redirectUri: 'https://usareboot.ru/vkAuth'
        pathPhoto: '/usr/vk_img/'
        redirectStandaloneUri: 'https://usareboot.ru/vkAuth'
    client:
        id: '51727454'
        secret: 'Lp8in0hLVi4I7SR7VMKz'
        standaloneId: '53265929'
        secretStandalone: 'nTITx5lir3dNSjKk6jAj'
