spring:
#    profiles:
#        active: test
    jpa:
        hibernate:
            default_schema: public
        show-sql: false
        properties:
            hibernate:
    datasource:
        usareboot:
            url: jdbc:postgresql://localhost:5432/dbusareboot
            username: usareboot
            password: Katerina_2022
            driver-class-name: org.postgresql.Driver
            schema: public
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect

vk:
    api:
        groupId: '224336762'
        chatId: '4'
        version: '5.139'
        redirectUri: 'https://usareboot.ru/vkAuth'
        pathPhoto: '/usr/vk_img/'
        redirectStandaloneUri: 'https://usareboot.ru/vkAuth'
    client:
        id: '51727454'
        secret: 'Lp8in0hLVi4I7SR7VMKz'
        standaloneId: '53265929'
        secretStandalone: 'nTITx5lir3dNSjKk6jAj'
logging:
    level:
#        root: INFO
#        org.springframework.web: DEBUG          # Логи Spring Web только от WARN
#        com.usareboot.back.VkApiClient: TRACE               # Все ваши классы в DEBUG
#        com.usareboot.back: DEBUG
#        com.vk.api.sdk: DEBUG # VK SDK (пакет по умолчанию)
        # HTTP-клиент внутри SDK
#        org.apache.http: WARN
#        org.apache.http.wire: ERROR          # Все ваши классы в DEBUG
