spring:
#    profiles:
#        active: localhost
    jpa:
        show-sql: false
        properties:
            hibernate:
    datasource:
        usareboot:
            url: jdbc:postgresql://77.222.58.194:5432/dbusareboot
            username: usareboot
            password: Katerina_2022
            driver-class-name: org.postgresql.Driver
            schema: public
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
#        hikari:
#            minimumIdle: 2
#            maximumPoolSize: 10
#            idleTimeout: 120000
#            connectionTimeout: 300000
#            maxLifetime: 6000000
vk:
    api:
        groupId: '224336762'
        chatId: '4'
        version: '5.139'
        redirectUri: 'https://localhost:80/vkAuth'
        pathPhoto: '/vk_img/'
        redirectStandaloneUri: 'https://localhost/vkAuth'
    client:
        id: '51727454'
        secret: 'Lp8in0hLVi4I7SR7VMKz'
        standaloneId: '53265929'
        secretStandalone: 'nTITx5lir3dNSjKk6jAj'
