spring:
    config:
        activate:
            on-profile: test
    jpa:
        show-sql: false
        properties:
            hibernate:
    datasource:
#        url: jdbc:postgresql://ep-cold-king-62125412.us-east-1.aws.neon.tech/usa_reboot
        url: jdbc:postgresql://217.107.219.182:5432/usareboot
#        url: jdbc:postgresql://localhost:5432/usareboot
        username: postgres
        password: Katerina2022
        driver-class-name: org.postgresql.Driver
#        hikari:
#            maxLifeTime:6000000 #10 minutes wait time
        hikari:
            minimumIdle: 2
            maximumPoolSize: 10
            idleTimeout: 120000
            connectionTimeout: 300000
            maxLifetime: 6000000
    cloud:
        openfeign:
            client:
                config:
                    default:
                        read-timeout: 300000
                        connect-timeout: 30000
                        loggerLevel: full

server:
    port: 9000

springdoc:
    show-actuator: true
    swagger-ui:
        enabled: true
        path: swagger-ui.html

jwt:
    header:
        Authorization
    secret:
        spmi
    time:
        expired:
            5000
        accept:
            300
    issuer:
        app
vk:
    groupId: '224336762'
    version: '5.139'
    redirectUrl: 'https://localhost:80/vkAuth'
    pathPhoto: ''

---

spring:
    config:
        activate:
            on-profile: prod
    jpa:
        show-sql: false
        properties:
            hibernate:
    datasource:
        #        url: jdbc:postgresql://ep-cold-king-62125412.us-east-1.aws.neon.tech/usa_reboot
        url: jdbc:postgresql://localhost:5432/usareboot
        username: postgres
        password: Katerina2022
        driver-class-name: org.postgresql.Driver
#    cloud:
#        openfeign:
#            client:
#                config:
#                    default:
#                        read-timeout: 300000
#                        connect-timeout: 30000
#                        logger-level: full
server:
    port: 9000

springdoc:
    show-actuator: true
    swagger-ui:
        enabled: true
        path: swagger-ui.html

jwt:
    header:
        Authorization
    secret:
        spmi
    time:
        expired:
            5000
        accept:
            300
    issuer:
        app
vk:
    api:
        groupId: '224336762'
        version: '5.139'
        redirectUri: 'https://usareboot.ru/vkAuth'
        pathPhoto: '/usr/vk_img/'
        clientId: '51727454'
        secret: 'Lp8in0hLVi4I7SR7VMKz'