spring:

    jpa:
#        hibernate:
#            dll-auto: create-drop
        show-sql: false
#        properties:
#            hibernate:
##                hbm2ddl:
##                    auto: update


    datasource:
        url: jdbc:postgresql://db22.spmi.edu.ru:5432/university
        username: university_db
        password: osiris
        driver-class-name: org.postgresql.Driver
#    flyway:
#        baseline-on-migrate: true
server:
    port: 9000

springdoc:
    show-actuator: true
    swagger-ui:
        enabled: true
        path: swagger-ui.html

jwt:
    header:
        Authorization
    secret:
        spmi
    time:
        expired:
            5000
        accept:
            300
    issuer:
        app